# Generated by Django 4.2.16 on 2025-09-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='Enter 12-digit Aadhaar number', max_length=12, null=True, unique=True),
        ),
    ]
