# Generated by Django 4.2.16 on 2025-09-04 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_donor_aadhaar_number'),
        ('blood', '0004_bloodrequest_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('blood_bank_available', models.BooleanField(default=True)),
                ('is_partner', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsors/')),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('FIRST_DONATION', 'First Time Donor'), ('REGULAR_DONOR', 'Regular Donor (5+ donations)'), ('HERO_DONOR', 'Hero Donor (10+ donations)'), ('LIFE_SAVER', 'Life Saver (20+ donations)'), ('BLOOD_CHAMPION', 'Blood Champion (50+ donations)')], max_length=20)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('donation_count', models.PositiveIntegerField()),
                ('certificate_id', models.CharField(max_length=20, unique=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donor')),
            ],
        ),
        migrations.CreateModel(
            name='BloodCamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('organizer', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('target_donors', models.PositiveIntegerField(default=50)),
                ('registered_donors', models.PositiveIntegerField(default=0)),
                ('actual_donors', models.PositiveIntegerField(default=0)),
                ('blood_collected', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('hospital_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood.hospital')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='CampRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('donated', models.BooleanField(default=False)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.bloodcamp')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donor')),
            ],
            options={
                'unique_together': {('camp', 'donor')},
            },
        ),
    ]
